#!/usr/bin/env php
<?php

if ( !file_exists ('composer.json') ) {
    echo "composer.json 파일이 존재하지 않습니다.\n";
    exit();
}

if ( !file_exists ('composer.dev') ) {
    echo "composer.dev 파일이 존재하지 않습니다.\n";
    exit();
}

$composer_json = file_get_contents('composer.json');
$json_obj = json_decode($composer_json, true);

$dev_mode = isset($json_obj['repositories']);

if ($dev_mode) {
    unset($json_obj['repositories']);
    file_put_contents('composer.json', json_encode($json_obj, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
    echo "이제 배포 모드 입니다.\n";
} else {
    file_put_contents('composer.json', file_get_contents('composer.dev'));
    echo "이제 개발 모드 입니다.\n";
}
